<?php

namespace Database\Seeders;

use App\Models\Category;
use Illuminate\Database\Seeder;

class CategorySeeder extends Seeder
{
    /**
     * The 6 canonical categories from SPEC §4.3.
     *
     * @var array<int, string>
     */
    private array $categories = [
        'billing',
        'technical',
        'account',
        'general',
        'bug',
        'feature-request',
    ];

    /**
     * Seed the categories table.
     *
     * Uses firstOrCreate so re-runs are idempotent.
     * Slug is auto-generated by Category::creating event — do NOT set manually.
     */
    public function run(): void
    {
        foreach ($this->categories as $name) {
            Category::firstOrCreate(['name' => $name]);
        }

        $this->command->info('CategorySeeder: seeded '.count($this->categories).' categories.');
    }
}
